// <auto-generated> by scripts/xamlcheck.py: every PackIcon Kind used in UI/*.xaml.
// The compile check fails here when MaterialDesignThemes has no icon of that name.
namespace SoundCalcs.CompileCheck
{
    internal static class XamlIcons
    {
        internal static readonly MaterialDesignThemes.Wpf.PackIconKind[] Used =
        {
            MaterialDesignThemes.Wpf.PackIconKind.AlertCircle,
            MaterialDesignThemes.Wpf.PackIconKind.ArrowRight,
            MaterialDesignThemes.Wpf.PackIconKind.AutoFix,
            MaterialDesignThemes.Wpf.PackIconKind.CalculatorVariantOutline,
            MaterialDesignThemes.Wpf.PackIconKind.ChartBoxOutline,
            MaterialDesignThemes.Wpf.PackIconKind.CheckCircle,
            MaterialDesignThemes.Wpf.PackIconKind.CheckCircleOutline,
            MaterialDesignThemes.Wpf.PackIconKind.ChevronDown,
            MaterialDesignThemes.Wpf.PackIconKind.ChevronRight,
            MaterialDesignThemes.Wpf.PackIconKind.CloseCircle,
            MaterialDesignThemes.Wpf.PackIconKind.CrosshairsGps,
            MaterialDesignThemes.Wpf.PackIconKind.CursorDefaultClickOutline,
            MaterialDesignThemes.Wpf.PackIconKind.FitToScreenOutline,
            MaterialDesignThemes.Wpf.PackIconKind.FlashOutline,
            MaterialDesignThemes.Wpf.PackIconKind.FloorPlan,
            MaterialDesignThemes.Wpf.PackIconKind.InformationOutline,
            MaterialDesignThemes.Wpf.PackIconKind.PinOffOutline,
            MaterialDesignThemes.Wpf.PackIconKind.PlayCircleOutline,
            MaterialDesignThemes.Wpf.PackIconKind.Refresh,
            MaterialDesignThemes.Wpf.PackIconKind.SpeakerMultiple,
            MaterialDesignThemes.Wpf.PackIconKind.StopCircleOutline,
            MaterialDesignThemes.Wpf.PackIconKind.TrayArrowDown,
            MaterialDesignThemes.Wpf.PackIconKind.TuneVariant,
            MaterialDesignThemes.Wpf.PackIconKind.Undo,
            MaterialDesignThemes.Wpf.PackIconKind.UnfoldMoreHorizontal,
            MaterialDesignThemes.Wpf.PackIconKind.VectorPolyline,
            MaterialDesignThemes.Wpf.PackIconKind.Waveform,
            MaterialDesignThemes.Wpf.PackIconKind.WeatherNight,
            MaterialDesignThemes.Wpf.PackIconKind.WindowClose,
            MaterialDesignThemes.Wpf.PackIconKind.WindowMaximize,
            MaterialDesignThemes.Wpf.PackIconKind.WindowMinimize,
        };
    }
}
